name: Workflow Commands Demo
on: push
jobs:
  workflow-cmd-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Group logs
        run: |
          echo "::group::My Group Logs"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
      
      - name: Step 1
        run: echo "MY_NAME=sunless" >> $GITHUB_ENV

      - name: Step 2
        run: echo "The value of MY_NAME is $MY_NAME"
      

